'use client';

import React, { useState, useRef, useEffect } from 'react';
import { Send, Copy, Download, User, Bot, Check, AlertCircle } from 'lucide-react';

interface Chunk {
  chunk_index: number;
  text: string;
  score: number;
}

interface Message {
  role: 'user' | 'assistant';
  content: string;
  method?: 'prompt' | 'rag';
  citations?: string[];
  chunks?: Chunk[];
}

interface ChatBoxProps {
  documentId: string;
  onSelectChunks: (chunks: Chunk[] | null) => void;
}

export default function ChatBox({ documentId, onSelectChunks }: ChatBoxProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Clear chat history when document changes
    setMessages([]);
    setSessionId(null);
    onSelectChunks(null);
  }, [documentId]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || loading) return;

    const userMsg = input.trim();
    setInput('');
    setMessages((prev) => [...prev, { role: 'user', content: userMsg }]);
    setLoading(true);

    try {
      const response = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentId,
          question: userMsg,
          sessionId: sessionId || undefined,
        }),
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.detail || 'An error occurred while getting answer.');
      }

      const data = await response.json();
      if (data.sessionId) {
        setSessionId(data.sessionId);
      }

      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          content: data.answer,
          method: data.method,
          citations: data.citations || [],
          chunks: data.chunks || [],
        },
      ]);
    } catch (err: any) {
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          content: `⚠️ Error: ${err.message || 'Could not fetch response. Please verify backend is running.'}`,
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const downloadAsTxt = (text: string, qText: string) => {
    const fileContent = `Question:\n${qText}\n\nAnswer:\n${text}\n\nGenerated by AuraDoc Q&A`;
    const element = document.createElement('a');
    const file = new Blob([fileContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `answer_${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="w-full flex flex-col h-[550px] rounded-2xl glass-panel bg-zinc-900/20 overflow-hidden border border-zinc-800">
      {/* Header */}
      <div className="px-6 py-4 border-b border-zinc-800 bg-zinc-900/40 flex justify-between items-center">
        <div className="flex items-center gap-2">
          <div className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-ping" />
          <h2 className="text-sm font-semibold text-zinc-200">Active Document Assistant</h2>
        </div>
        {sessionId && (
          <span className="text-zinc-500 text-[10px] bg-zinc-800/80 px-2 py-0.5 rounded border border-zinc-700">
            Session ID: {sessionId.slice(0, 8)}...
          </span>
        )}
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {messages.length === 0 && (
          <div className="h-full flex flex-col items-center justify-center text-zinc-500 space-y-2">
            <Bot className="w-12 h-12 text-zinc-700" />
            <p className="text-sm font-medium">Ask any question about the document content.</p>
            <p className="text-xs text-zinc-600 text-center max-w-xs">
              Answers are grounded strictly in the source text.
            </p>
          </div>
        )}

        {messages.map((msg, idx) => {
          const isUser = msg.role === 'user';
          return (
            <div key={idx} className={`flex gap-4 ${isUser ? 'justify-end' : 'justify-start'}`}>
              {!isUser && (
                <div className="w-8 h-8 rounded-full bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shrink-0">
                  <Bot className="w-4 h-4" />
                </div>
              )}

              <div className={`flex flex-col max-w-[80%] space-y-1.5`}>
                <div className={`p-4 rounded-2xl text-sm leading-relaxed border ${
                  isUser 
                    ? 'bg-indigo-600 text-white border-indigo-500 rounded-tr-none' 
                    : 'bg-zinc-900/70 text-zinc-200 border-zinc-800 rounded-tl-none'
                }`}>
                  <p className="whitespace-pre-wrap">{msg.content}</p>
                </div>

                {/* Assistant metadata & actions */}
                {!isUser && !msg.content.startsWith('⚠️') && (
                  <div className="flex flex-col gap-2 px-1">
                    {/* Method, Citations & Action triggers */}
                    <div className="flex flex-wrap items-center gap-3 text-xs text-zinc-500">
                      {msg.method && (
                        <span className={`px-2 py-0.5 rounded text-[10px] font-semibold border ${
                          msg.method === 'prompt' 
                            ? 'bg-amber-500/5 text-amber-400/90 border-amber-500/15' 
                            : 'bg-cyan-500/5 text-cyan-400/90 border-cyan-500/15'
                        }`}>
                          {msg.method === 'prompt' ? 'Prompt Mode' : 'RAG Mode'}
                        </span>
                      )}

                      <button
                        onClick={() => copyToClipboard(msg.content, idx)}
                        className="flex items-center gap-1 hover:text-zinc-300 transition text-[11px]"
                      >
                        {copiedIndex === idx ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                            <span>Copied</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>

                      <button
                        onClick={() => downloadAsTxt(msg.content, messages[idx - 1]?.content || '')}
                        className="flex items-center gap-1 hover:text-zinc-300 transition text-[11px]"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>Download</span>
                      </button>

                      {msg.chunks && msg.chunks.length > 0 && (
                        <button
                          onClick={() => onSelectChunks(msg.chunks || null)}
                          className="text-indigo-400/90 hover:text-indigo-300 text-[11px] font-semibold transition"
                        >
                          Inspect Chunks ({msg.chunks.length})
                        </button>
                      )}
                    </div>

                    {/* Citations list */}
                    {msg.citations && msg.citations.length > 0 && (
                      <div className="mt-1">
                        <span className="text-[10px] uppercase font-bold text-zinc-600 block mb-1">Sources Cited:</span>
                        <div className="flex flex-wrap gap-1.5">
                          {msg.citations.map((cite, cIdx) => (
                            <span key={cIdx} className="bg-zinc-900 text-zinc-400 border border-zinc-800 text-[10px] px-2 py-0.5 rounded">
                              {cite}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {isUser && (
                <div className="w-8 h-8 rounded-full bg-zinc-800 border border-zinc-700 flex items-center justify-center text-zinc-300 shrink-0">
                  <User className="w-4 h-4" />
                </div>
              )}
            </div>
          );
        })}

        {loading && (
          <div className="flex gap-4 justify-start">
            <div className="w-8 h-8 rounded-full bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shrink-0">
              <Bot className="w-4 h-4" />
            </div>
            <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl rounded-tl-none p-4 max-w-[80%] flex items-center gap-2.5">
              <span className="w-2 h-2 rounded-full bg-indigo-500 animate-bounce [animation-delay:-0.3s]"></span>
              <span className="w-2 h-2 rounded-full bg-indigo-500 animate-bounce [animation-delay:-0.15s]"></span>
              <span className="w-2 h-2 rounded-full bg-indigo-500 animate-bounce"></span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <form onSubmit={handleSubmit} className="p-4 border-t border-zinc-800 bg-zinc-900/40 flex gap-2">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask a question about the document..."
          className="flex-1 bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-200 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 placeholder-zinc-600 transition"
        />
        <button
          type="submit"
          disabled={!input.trim() || loading}
          className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-zinc-800 disabled:text-zinc-600 text-white font-medium p-2.5 px-4 rounded-xl text-sm transition flex items-center justify-center shrink-0 gap-1.5"
        >
          <span className="hidden sm:inline">Ask</span>
          <Send className="w-4 h-4" />
        </button>
      </form>
    </div>
  );
}
